services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb-compose
    environment:
      MYSQL_ROOT_PASSWORD: BROCSM
      MYSQL_DATABASE: EventosX
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
